# Generated by Django 5.2.5 on 2025-08-18 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_created',
            new_name='created_at',
        ),
    ]
